[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_counter = "3nnAhNGFcEEBZfpyjrL55dmpDZNavXEKpVKusfUFfzJ7"

[programs.localnet]
anchor_counter = "3nnAhNGFcEEBZfpyjrL55dmpDZNavXEKpVKusfUFfzJ7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc -p tsconfig.json && npx mocha --timeout 120000 dist/tests/settle-vault.js"